version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./var/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - 33066:3306
    php:
        build: ./docker/php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./var/logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
