version: '2'

services:

    web:
        build: .docker/apache
        networks:
            - default
            - web
        volumes_from:
            - php
        volumes:
            - ./logs:/var/log/apache2
        environment:
            VIRTUAL_HOST: 'symfony.${DEV_DOMAIN}'
            HTTPS_METHOD: ~
            CERT_NAME: ~
    # End web

    php:
        build: ./.docker/php7-fpm
        environment:
            SYMFONY_DEFAULT_LOCALE: ${SYMFONY_DEFAULT_LOCALE}
            DB_DRIVER:              ${DB_DRIVER}
            DB_HOST:                ${DB_HOST}
            DB_PORT:                ${DB_PORT}
            DB_DATABASE:            ${DB_DATABASE}
            DB_USER:                ${DB_USER}
            DB_PASSWORD:            ${DB_PASSWORD}
            MAILER_TRANSPORT:       ${MAILER_TRANSPORT}
            MAILER_HOST:            ${MAILER_HOST}
            MAILER_PORT:            ${MAILER_PORT}
            MAILER_USER:            ${MAILER_USER}
            MAILER_PASSWORD:        ${MAILER_PASSWORD}
        networks:
            - default
            - database
            - maildev
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
    # End php

    db:
        image: mysql
        ports:
            - 33066:3306
        networks:
            - database
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE:      ${DB_DATABASE}
            MYSQL_USER:          ${DB_USER}
            MYSQL_PASSWORD:      ${DB_PASSWORD}
    #End db

    #redis:
    #    image: redis:alpine
    #    ports:
    #        - 6379:63799
    # End redis

    #
    # Utils
    #
    maildev: #SMTP Port on 1025
        image: djfarrelly/maildev
        environment:
            VIRTUAL_HOST: maildev.${DEV_DOMAIN}

    # Little PMA in one file
    # But i recommend to connect directly to db via software db:mysql:33066
    adminer:
        image: dehy/adminer
        environment:
            VIRTUAL_HOST: adminer.${DEV_DOMAIN}
        networks:
            - web
            - database

    # NGINX PRoxy for virtual hosts
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        networks:
            - default
            - web
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro # Double first slash for windows //var/...

networks:
    web:
        driver: bridge
    maildev:
        driver: bridge
    database:
        driver: bridge

volumes:
    db_data:
        driver: local